

DELETE FROM titan_preliquidacion.detalle_preliquidacion
DELETE FROM titan_preliquidacion.concepto_nomina
DELETE FROM titan_preliquidacion.tipo_concepto_nomina
DELETE FROM titan_preliquidacion.estado_concepto_nomina
DELETE FROM titan_preliquidacion.naturaleza_concepto_nomina
DELETE FROM titan_preliquidacion.estado_disponibilidad
DELETE FROM titan_preliquidacion.tipo_preliquidacion
DELETE FROM titan_preliquidacion.preliquidacion
DELETE FROM titan_preliquidacion.nomina
DELETE FROM titan_preliquidacion.estado_preliquidacion
DELETE FROM titan_preliquidacion.tipo_nomina